// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "1yvojC7Mhk456R3FkDYp0joibBjjdJavnMztRp0oIOY6DrZNFs0RHeV4o5QWUGjO1bseMz";
}
}
}

